### ISSUE TITLE
与AndResGuard的兼容问题

### ISSUE THREAD

**Issue by weicheng791279106** [ltlovezh/ApkChannelPackage#1]
使用AndResGuard进行资源混淆后将资源混淆后生成的apk包再打多渠道包会报
not have precise channel package mode 错误。

**Comment by ltlovezh** [comment]
应该是AndResGuard进行了重新签名，我完善下检查V1签名的方式，多谢！

**Comment by ltlovezh** [comment]
最新的1.0.3已经完善了V1签名检测方式，Thanks！
