### ISSUE TITLE
Bug: rebuildChannel releaseOutputDir can't use exist folder

### ISSUE THREAD

**Issue by gengjiawen** [ltlovezh/ApkChannelPackage#12]
When releaseOutputDir is already exist in filesystem.
I get the following exception 
```
* What went wrong:
Execution failed for task ':passenger:reBuildChannel'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
If releaseOutputDir doesn't exist, everything works fine.

**Comment by ltlovezh** [comment]
the code is:
public boolean isNeedRebuildReleaseApk() {
        if (baseReleaseApk == null || !baseReleaseApk.exists() || !baseReleaseApk.isFile()) {
            println("baseReleaseApk : ${baseReleaseApk} , it is not a valid file , so can not rebuild release channel apk");
            return false
        } else {
            if (releaseOutputDir == null) {
                throw new GradleException("baseReleaseApk : ${baseReleaseApk} is ok , so you should set a valid releaseOutputDir , or you can set baseReleaseApk = null")
            }

            if (!releaseOutputDir.exists()) {
                releaseOutputDir.mkdirs()
            } else {
                // delete old apks
                releaseOutputDir.eachFile { file ->
                    if (file.name.endsWith(".apk")) {
                        file.delete()
                    }
                }
            }
            return true
        }
    }


and I didn't encounter this problem
