### ISSUE TITLE
请问本地仓库问题

### ISSUE THREAD

**Issue by dreamanli** [ltlovezh/ApkChannelPackage#13]
你好，我想对插件做点修改，在本地测试，一直没有变化，需要修改哪个几地方？

**Comment by ltlovezh** [comment]
repositories.mavenDeployer {
        repository(url: "file:///Users/zhangkaqi/localMaven")
    }

这里修改成自己的地址，然后在app的build.gradle文件里也修改成本地的仓库地址。
修改代码后，执行gradle install 就会部署到本地仓库
