### ISSUE TITLE
安装包损坏

### ISSUE THREAD

**Issue by kun1988** [ltlovezh/ApkChannelPackage#14]
WIN7下面打出来的渠道包安装到手机上，应用宝提示安装包损坏，另外打出来的渠道包都不能删除，提示被其他程序占用，mac下面使用这个渠道打包工具没问题

**Comment by ltlovezh** [comment]
请问你是V1签名打包还是V2签名打包哈，因为是基于gradle打包，理论上跟操作系统没有关系，而且我在window下也没遇到“提示被其他程序占用”的问题哈

**Comment by kun1988** [comment]
用的V2打包，不知道跟腾讯管家和应用宝是否有冲突。

**Comment by ltlovezh** [comment]
我这边又在Window上打了V2包，没遇到问题哈

**Comment by ltlovezh** [comment]
Hello，麻烦问下你们使用ApkChannelPackage的是什么APP哈

**Comment by kun1988** [comment]
抢票达人

**Comment by ltlovezh** [comment]
好的，多谢

**Comment by pdog18** [comment]
我也遇到了同样问题，一样是win10 使用应用宝安装，提示安装包错误，并且包也不能删除

**Comment by kun1988** [comment]
@pdog18 重启电脑

**Comment by pdog18** [comment]
@kun1988 嗯 是应用宝安装器的问题，用adb命令就可以正常安装，重启也能让应用宝安装器听话
