### ISSUE TITLE
channel.txt和productFlavors 冲突

### ISSUE THREAD

**Issue by zysidea** [ltlovezh/ApkChannelPackage#15]
比如channel.txt种有xiaomi，qihu，baidu三个渠道，productFlavors 也有这三个渠道，这种情况下如果执行Gradle命令channelxiaomiDebug只打包xiaomi渠道的，还是会生成xiaomi，qihu，baidu三个渠道包，并且这个三个渠道包在xiaomi的文件夹下。

**Comment by ltlovezh** [comment]
Hello，麻烦问下你们使用ApkChannelPackage的是什么APP哈
