### ISSUE TITLE
不会生成文件，而是变成目录

### ISSUE THREAD

**Issue by shiftwinting** [ltlovezh/ApkChannelPackage#153]
java version: 1.8
VasDolly: 3.0.6
java -jar /usr/local/walle/VasDolly.jar put -c "xxxx" 111.apk 12.apk
此时生成12.apk目录,而且是空有问题

**Comment by shiftwinting** [comment]
这种方式，它不能直接写文件

**Comment by icesquall** [comment]
请问问题解决了吗，我也遇到同样现象

**Comment by icesquall** [comment]
> 这种方式，它不能直接写文件
请问问题解决了吗，我也遇到同样现象
