### ISSUE TITLE
gradle版本最高支持到多少？在7.5上编译会出错

### ISSUE THREAD

**Issue by pglve** [ltlovezh/ApkChannelPackage#154]
* What went wrong:
Configuration cache problems found in this build.

3 problems were found storing the configuration cache, 2 of which seem unique.
- Task `:app:reBuildChannel` of type `com.tencent.vasdolly.plugin.task.RebuildApkChannelPackageTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:reBuildChannel` of type `com.tencent.vasdolly.plugin.task.RebuildApkChannelPackageTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

**Comment by fbu11** [comment]
是7.5的问题吧，我 gradle:8.0.2  agp:7.4.2都没事版本很高了，都没事

**Comment by NicodeLee** [comment]
不是gradle版本问题，我也遇到这个问题，换了几个gradle都一样。
目前调试中，看看有什么思路。
org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':app:reBuildChannel' at execution time is unsupported.
        at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onTaskExecutionAccessProblem(ConfigurationCacheProblemsListener.kt:101)
        at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onProjectAccess(ConfigurationCacheProblemsListener.kt:64)
        at jdk.internal.reflect.GeneratedMethodAccessor1769.invoke(Unknown Source)

**Comment by pglve** [comment]
设置org.gradle.unsafe.configuration-cache=false就好了
