### ISSUE TITLE
发现v1签名不支持

### ISSUE THREAD

**Issue by shiftwinting** [ltlovezh/ApkChannelPackage#155]
signature mode:V1
java -jar VasDolly.jar put -c "channn1" 111.apk /data/www/
111.apk not have channel info from Zip Comment
111.apk has a channel : , only ignore

**Comment by realityJie** [comment]
Util类里这段代码改成这样子：
        if (testChannel.isEmpty()) {
            System.out.println("baseApk : " + baseApk.getAbsolutePath() + " has a channel : " + testChannel + ", only ignore");
            return;
        }

**Comment by realityJie** [comment]
Util类的下边这段代码改成这样子：
        if (!testChannel.isEmpty()) {
            System.out.println("baseApk : " + baseApk.getAbsolutePath() + " has a channel : " + testChannel + ", only ignore");
            return;
        }

**Comment by shiftwinting** [comment]
好的，谢谢

**Comment by realityJie** [comment]
> 好的，谢谢

#158 可以看这个PR，还有其他地方需要修改
