### ISSUE TITLE
命令行工具能写入信息，但是验证失败

### ISSUE THREAD

**Issue by callmepeanut** [ltlovezh/ApkChannelPackage#18]
日志如下：
find V2 signature block Id : 1896449818
baseApk : C:\Users\...\app-release.apk , ChannelPackageMode : V2 Mode
------ File app-release.apk generate v2 channel apk  , begin ------
baseApk : C:\Users\...\app-release.apk , ApkSectionInfo = mContentEntry : first = java.nio.HeapByteBuffer[pos=0 lim=2572932 cap=2572932] , second = 0 , mSchemeV2Block : first = java.nio.HeapByteBuffer[pos=0 lim=1569 cap=1569] , second = 2572932 , mCentralDir : first = java.nio.HeapByteBuffer[pos=0 lim=43224 cap=43224] , second = 2574501 , mEocd : first = java.nio.HeapByteBuffer[pos=0 lim=22 cap=22] , second = 2617725
generateV2ChannelApk , channel = store_xiaomi , apkChannelName = store_xiaomi-app-release.apk
destApk = C:\Users\...\out\store_xiaomi-app-release.apk , channel = store_xiaomi
addIdValueByteBufferMap , idValueMap = {-2012129793=java.nio.HeapByteBuffer[pos=0 lim=12 cap=12]}
find V2 signature block Id : 1896449818
addIdValueByteBufferMap , existentIdValueMap = {1896449818=java.nio.HeapByteBuffer[pos=0 lim=1525 cap=1525]}
addIdValueByteBufferMap , finalIdValueMap = {1896449818=java.nio.HeapByteBuffer[pos=0 lim=1525 cap=1525], -2012129793=java.nio.HeapByteBuffer[pos=0 lim=12 cap=12]}
addIdValueByteBufferMap , oldApkSigningBlock size = 1569 , newApkSigningBlock size = 1593
addIdValueByteBufferMap , after add channel , new apk is C:\Users\...\out\store_xiaomi-app-release.apk , length = 2617771
try to read channel info from apk : C:\Users...\out\store_xiaomi-app-release.apk
find V2 signature block Id : 1896449818
getByteBufferValueById , destApk C:\Users\...\out\store_xiaomi-app-release.apk IdValueMap = {1896449818=java.nio.HeapByteBuffer[pos=0 lim=1525 cap=1525], -2012129793=java.nio.HeapByteBuffer[pos=0 lim=12 cap=12]}
getByteValueById , id = -2012129793 , value = java.nio.HeapByteBuffer[pos=0 lim=12 cap=12]
generateV2ChannelApk , .\out\store_xiaomi-app-release.apk add channel success
verified : false
generateV2ChannelApk error , please check it and fix it ▒▒and that you should generate all V2 Channel Apk again!
java.lang.RuntimeException: generateV2ChannelApk , after add channel , .\out\store_xiaomi-app-release.apk v1 verify failure
        at com.leon.channel.command.Util.generateV2ChannelApk(Util.java:241)
        at com.leon.channel.command.Util.writeChannel(Util.java:92)
        at com.leon.channel.command.Main.main(Main.java:110)
------ File app-release.apk generate v2 channel apk , end ------
------ total 1 channel apk , cost : 136 ------

**Comment by callmepeanut** [comment]
是使用的包有问题，替换base包后没问题了

**Comment by ltlovezh** [comment]
Hello，麻烦问下你们使用ApkChannelPackage的是什么APP哈

**Comment by callmepeanut** [comment]
@ltlovezh 还在开发中，没发布~

**Comment by ltlovezh** [comment]
好的，谢谢
