### ISSUE TITLE
java.lang.Exception: zip v1 magic not found

### ISSUE THREAD

**Issue by memorycj** [ltlovezh/ApkChannelPackage#19]
你好 ，读取channel时出现 java.lang.Exception: zip v1 magic not found 是什么原因造成的？

**Comment by zysidea** [comment]
@memorycj 你好，你运行下 unzip -z xxx.apk，把输出结果发过来。

**Comment by memorycj** [comment]
@zysidea 是不是要channekxxx 任务打出来的包才可以去读取？否则就会有概率出这个问题 ？

**Comment by zysidea** [comment]
@memorycj 读取channel的前提是是带有channel的包才能读出来，没有概率一说

**Comment by memorycj** [comment]
@zysidea sry，用词不当，那我大概知道什么问题了。打扰了哈

**Comment by zysidea** [comment]
@memorycj 没事

**Comment by ltlovezh** [comment]
java.lang.Exception: zip v1 magic not found 表示没有写入渠道信息哈，只有写入渠道信息的渠道包才能读出渠道信息哈

**Comment by ltlovezh** [comment]
麻烦问下你们使用ApkChannelPackage时什么APP哈

**Comment by ltlovezh** [comment]
Hello，麻烦问下你们使用ApkChannelPackage的是什么APP哈
