### ISSUE TITLE
如果有加固的需求的话，该怎么使用呢

### ISSUE THREAD

**Issue by xingstarx** [ltlovezh/ApkChannelPackage#2]
看了你的文章介绍，如果有加固需求的话，这种改怎么弄了。

我们的场景如下，首先打出一个未签名的apk，然后使用梆梆加固，加固后添加渠道列表，得到10多个渠道包，然后再签名。这种场景下。怎么使用tinker的热修复呢。也就是我加固后的渠道包，他们的crc应该都不一样了吧。

**Comment by ltlovezh** [comment]
Tinker目前支持梆梆加固吗？你这种方式每个APK的Dex的CRC值肯定不一样。
可以这样：首先打出一个未签名的apk，然后使用梆梆加固，然后签名（V1或者V2）。得到一个签名后的APK，然后使用APKChannelPackage进行添加渠道（选择根据已有APK生成渠道包模式）。

**Comment by xingstarx** [comment]
按照 @ltlovezh 的提示是可以的。
1. 首先打一个签名的apk包
2. 梆梆加固(梆梆加固自带的签名工具使用的是v1签名)
3. 将加固后的apk放到baseApk目录下，按照文档上的配置 reBuildChannel(也就是根据已有apk生成渠道包的模式)

**Comment by gmfbilu** [comment]
请问你是怎么做的啊，我打包后加固就读不到渠道信息了

**Comment by ltlovezh** [comment]
1. 先打基础包
2. 加固
3.签名
4.添加渠道信息

（添加渠道信息一定要是最后一步）

**Comment by xingstarx** [comment]
@ltlovezh 总结的很好

**Comment by chensong1993** [comment]
渠道包打好了但是补丁包还是没起作用,补丁包是打之前基础包的还是渠道包的

**Comment by ltlovezh** [comment]
补丁包针对基础包打就好了，如果每个渠道包都生成补丁包，那岂不是也累死...
