### ISSUE TITLE
请问我用乐加固加固了热修复的app后，baseReleaseApk怎么配置

### ISSUE THREAD

**Issue by ldlywt** [ltlovezh/ApkChannelPackage#20]
我完成了乐加固，再根据乐加固生成了热修复的多聚到包，但是如果再集成了腾讯的MTA统计，又该怎么配置才能识别各个各个渠道的统计？

**Comment by ldlywt** [comment]
现在mta的统计功能都是在gradle里面配置
```
        manifestPlaceholders = [
                MTA_APPKEY   : "xxxxxx",
                MTA_CHANNEL  : "通用渠道"
        ]
```
在MTA_CHANNEL  这个字段里面怎么调用ChannelReaderUtil.getChannel(getApplicationContext())这个方法上传呢

**Comment by ltlovezh** [comment]
我们也使用了MTA，MTA有API支持可以直接设置渠道信息，不一定要通过上面的方式来设置，请仔细阅读下MTA的文档哈。

**Comment by ltlovezh** [comment]
麻烦问下你们使用ApkChannelPackage时什么APP哈

**Comment by ldlywt** [comment]
因为项目中要，集成热修复、加固、多渠道，我现在使用个bugly的热修复+腾讯乐固+腾讯MTA统计+ApkChannelPackage多渠道打包，现在还没遇到兼容问题。
顺便说下：ApkChannelPackage多渠道打包速度真的快，几分钟就打了10个包

**Comment by ltlovezh** [comment]
恩恩，我们也使用了MTA，有问题欢迎反馈
