### ISSUE TITLE
使用rebuildChannel 根据已有基础包重新生成多渠道包有问题

### ISSUE THREAD

**Issue by fanturbo** [ltlovezh/ApkChannelPackage#23]
<pre>channel{
    //指定渠道文件
    channelFile = file("../channel.txt")
    //多渠道包的输出目录，默认为new File(project.buildDir,"channel")
    baseOutputDir = new File(project.buildDir,"channel")
    //多渠道包的命名规则，默认为：${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}
    apkNameFormat ='${appName}-${versionName}-${versionCode}-${flavorName}-${buildType}'
}

rebuildChannel {
    //指定渠道文件
    channelFile = new File("../channel.txt")
    baseReleaseApk = new File(project.buildDir, "outputs/apk/app-release.apk")
    //默认为new File(project.buildDir, "rebuildChannel/release")
    releaseOutputDir = new File(project.buildDir, "rebuildChannel/release")
}</pre>
上面是我的配置，但是执行rebuildChannel之后只有一个渠道包（rebuildChannel\release目录下只有一个app-release.apk文件）生成，是怎么回事呢？ps：执行channel命令打渠道包是正常的

**Comment by ltlovezh** [comment]
这里“rebuildChannel”生成渠道包时，会用新渠道名替换已有基础包的“base”字符串，但是"outputs/apk/app-release.apk"不包含“base”字符串，所以新的渠道包名字还是app-release.apk，因此后面的APK就把前面的覆盖了，最后只出现一个。短期解决就是改下基础包的命名“app-base-release.apk”，后续我发个版本fix下这个问题

**Comment by baixxx** [comment]
请问一下,配置好之后，执行rebuildChannel并没有生成rebuildChannel目录

**Comment by ltlovezh** [comment]
之星有错误吗

**Comment by ltlovezh** [comment]
执行有错误吗

**Comment by baixxx** [comment]
没有报错
