### ISSUE TITLE
含有AAR模块的工程如何使用ApkChannelPackage

### ISSUE THREAD

**Issue by dreamanli** [ltlovezh/ApkChannelPackage#4]
Error:(3, 0) plugin 'com.android.application' must be apply
AAR模块的build.grale 没有  com.android.application，报错

**Comment by ltlovezh** [comment]
这个跟AAR没什么关系吧，看下接入文档。使用本插件，需要添加插件引用：apply plugin: 'channel'

**Comment by dreamanli** [comment]
加 apply plugin: 'channel' 就需要apply plugin: 'com.android.application'，但是我们的模块是没有 apply plugin: 'com.android.application'的，所以就报错了

**Comment by ltlovezh** [comment]
子模块只是一个aar，不需要单独打包吧，主要还是在生成APK的时候才会使用到。
