### ISSUE TITLE
要求minSdkVersion至少是16

### ISSUE THREAD

**Issue by dreamanli** [ltlovezh/ApkChannelPackage#5]

**Comment by johnwatsondev** [comment]
你好，方便发下环境配置和错误日志吗？谢谢。

**Comment by dreamanli** [comment]
Error:Execution failed for task ':huxin_app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.leon.channel:helper:1.0.2] APP路径\build\intermediates\exploded-aar\com.leon.channel\helper\1.0.2\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="leon.com.helper" to force usage

**Comment by dreamanli** [comment]
app :

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'

    lintOptions {
        abortOnError false
    }
。。。
｝


 项目
        classpath 'com.android.tools.build:gradle:2.2.3'

**Comment by johnwatsondev** [comment]
你好，目前暂时不知道为何 `minSdkVersion` 为何为 16，有一个尝试办法：可以自己修改根项目目录下的 `build.gradle` 中的 `minSdkVersion = 16` 为 14，并且修改 `url "file:///Users/zhangkaqi/localMaven"`。

我的意思：自己搭建搭建本地 maven 仓库，重新编译下 plugin，publish 到本地 maven 仓库，然后依赖构建。

**Comment by ltlovezh** [comment]
最新的1.0.3已修改成14哈

**Comment by ltlovezh** [comment]
Hello，麻烦问下你们使用ApkChannelPackage的是什么APP哈
