### ISSUE TITLE
AndroidManifest.xml  中<application         android:allowBackup="false"  编译报错

### ISSUE THREAD

**Issue by dreamanli** [ltlovezh/ApkChannelPackage#6]
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(true) from AndroidManifest.xml:6:9-35
	is also present at [com.leon.channel:helper:1.0.2] AndroidManifest.xml:12:9-36 value=(false).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.

**Comment by johnwatsondev** [comment]
日志已经给出了解决方案：添加 `tools:replace="android:allowBackup` 到可运行 module 的 AndroidManifest.xml 的 `<application/>` 标签中：

```
<application
      android:allowBackup="true"
      android:icon="@mipmap/ic_launcher"
      android:label="@string/app_name"
      android:theme="@style/AppTheme"
      tools:replace="android:allowBackup"/>
```

**Comment by ltlovezh** [comment]
恩，麻烦更新到 1.0.2哈

**Comment by xingstarx** [comment]
@ltlovezh  目前还是有这个问题额

```
* What went wrong:
Execution failed for task ':app:processReleaseManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(true) from AndroidManifest.xml:9:9-35
        is also present at [com.leon.channel:helper:1.0.3] AndroidManifest.xml:12:9-36 value=(false).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:8:5-35:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


```

**Comment by ltlovezh** [comment]
首先，这个application@allowBackup一般设置为false，否则可能存在安全性问题。
如果你一定要设置为true。错误中也给出了修改意见哈

**Comment by ltlovezh** [comment]
我把android:allowBackup这货删了吧

**Comment by xingstarx** [comment]
嗯，还是删除了好
